-- ===========================================================================
-- RUN THIS ONCE, WHOLE FILE, IN: Supabase Dashboard → SQL Editor → New query
-- ===========================================================================
-- Order ids used to be made up in the browser — 'PC' + Math.random() over a
-- 6-digit range, so about 900,000 possibilities, generated by a source that
-- isn't cryptographically random to begin with. send-order-confirmation
-- takes only an orderId and no auth (by design, so a customer's own browser
-- can call it right after checkout), so a 900,000-value space is small enough
-- to brute-force: script through every PC______ id and real customers get
-- repeat "order confirmed" mail, and an attacker learns which ids are real.
--
-- This moves id generation into place_order itself — the one place an order
-- can be created — using Postgres's random() over a 10-digit range (10
-- billion possibilities) instead of the client's guess. The retry loop below
-- covers the astronomically rare case of two orders landing on the same
-- random id; it never redoes the stock check above it, only the insert.
--
-- The 'PC' (storefront) / 'PM' (manual/DM sale) prefix stays, now chosen by
-- the caller via order.id_prefix instead of baked into a client-side string,
-- and anything other than those two collapses to 'PC' rather than accepting
-- arbitrary text.

begin;

create or replace function place_order(payload jsonb)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  o          jsonb := payload -> 'order';
  id_prefix  text  := case when (o ->> 'id_prefix') in ('PC', 'PM')
                        then o ->> 'id_prefix' else 'PC' end;
  new_id     text;
  attempt    int := 0;
  item       jsonb;
  cur_stock  jsonb;
  has_row    boolean;
  left_count int;
  want       int;
  size_key   text;
begin
  if jsonb_typeof(payload -> 'items') <> 'array'
     or jsonb_array_length(payload -> 'items') = 0 then
    raise exception 'EMPTY_CART';
  end if;

  -- Stock first: no order row is written for a cart that can't be filled.
  for item in select * from jsonb_array_elements(payload -> 'items')
  loop
    size_key := item ->> 'size';
    want := (item ->> 'qty')::int;

    select p.stock, true into cur_stock, has_row
      from products p
     where p.id::text = item ->> 'product_id'
       for update;

    if not coalesce(has_row, false) then
      raise exception 'UNAVAILABLE:%', item ->> 'product_name';
    end if;

    if cur_stock is not null then
      left_count := coalesce((cur_stock ->> size_key)::int, 0);

      if left_count < want then
        raise exception 'SOLD_OUT:%:%', item ->> 'product_name', size_key;
      end if;

      update products
         set stock = jsonb_set(stock, array[size_key], to_jsonb(left_count - want))
       where id::text = item ->> 'product_id';
    end if;
  end loop;

  -- Id generated here, not trusted from the caller — retried only on the
  -- (extremely unlikely) collision, so the stock already taken above is
  -- never double-counted.
  loop
    new_id := id_prefix || lpad(floor(random() * 10000000000)::bigint::text, 10, '0');

    begin
      insert into orders (
        id, customer_name, customer_phone, customer_email, customer_address,
        customer_area, customer_note, subtotal, delivery_zone, delivery_fee,
        total, advance_amount, advance_method, advance_trx_id,
        utm_source, utm_medium, utm_campaign, utm_content, utm_term
      ) values (
        new_id,
        o ->> 'customer_name',
        o ->> 'customer_phone',
        o ->> 'customer_email',
        o ->> 'customer_address',
        o ->> 'customer_area',
        o ->> 'customer_note',
        (o ->> 'subtotal')::numeric,
        o ->> 'delivery_zone',
        (o ->> 'delivery_fee')::numeric,
        (o ->> 'total')::numeric,
        (o ->> 'advance_amount')::numeric,
        o ->> 'advance_method',
        o ->> 'advance_trx_id',
        o ->> 'utm_source',
        o ->> 'utm_medium',
        o ->> 'utm_campaign',
        o ->> 'utm_content',
        o ->> 'utm_term'
      );
      exit;
    exception when unique_violation then
      attempt := attempt + 1;
      if attempt >= 5 then
        raise exception 'ORDER_ID_COLLISION';
      end if;
    end;
  end loop;

  insert into order_items (order_id, product_id, product_name, size, price, qty)
  select
    new_id,
    e.value ->> 'product_id',
    e.value ->> 'product_name',
    e.value ->> 'size',
    (e.value ->> 'price')::numeric,
    (e.value ->> 'qty')::int
  from jsonb_array_elements(payload -> 'items') as e;

  return new_id;
end;
$$;

revoke all on function place_order(jsonb) from public;
grant execute on function place_order(jsonb) to anon, authenticated;

commit;
