// Writes public/_headers from worker/security-headers.js right before
// `vite build` copies public/ into dist/, so the headers Cloudflare puts on
// static files and the ones the Worker puts on /product/* come from one list
// and can't drift apart.

import { writeFileSync } from 'node:fs'
import { SECURITY_HEADERS } from '../worker/security-headers.js'

const lines = Object.entries(SECURITY_HEADERS).map(([name, value]) => `  ${name}: ${value}`)

writeFileSync(
  'public/_headers',
  `# Generated by scripts/generate-headers.mjs from worker/security-headers.js — edit that file, not this one.\n/*\n${lines.join('\n')}\n`
)
console.log(`[headers] Wrote ${lines.length} security headers to public/_headers.`)
